---
- name: Update APT
  hosts: all
  become: true

  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes

    - name: Clean up APT cache
      apt:
        autoclean: yes
        autoremove: yes
